### ISSUE TITLE
implement neopixel patterns

### ISSUE THREAD

**Issue by securelyfitz** [Blevene/LabsConBadge_2023#24]
likely plenty of open source examples to choose from. Should probably include at least:
- rainbow cycle across leds
- rainbow cycle, all leds in sync- chaser/marquee
- heartbeat
- fire
- flashlight

these patterns should be contained in a separate .py file with comments to tell end users how to modify them
The current pattern should be selectable from the settings menu.

**Comment by psifertex** [comment]
I noticed the gc was interrupting the animation (I know it'll go away once done but for now just re-ordering it smooths out animations) and I also split up the animation style and color into two settings.

**Comment by securelyfitz** [comment]
awesome - i added excessive gc in an unsuccesful attempt to resolve the RX issue which at first i though was running out of memory, but now i think is memory corruption related.

**Comment by psifertex** [comment]
Added brightness setting, cleaned up the sparkle pattern which wasn't really working and added chase.

**Comment by psifertex** [comment]
Probably can close this one out at this point, lights are pretty full featured.

**Comment by securelyfitz** [comment]
thanks again. I moved gc to the gamedata class after a new clue is added, since that's where the most memory collection happens.
